spring:
  profiles:
    active:
    - cat
    - EN
    - prod
guru:
  username: YmlUserName
  password: YmlPwd
  jdbcurl: YmlJdbcUrl

---
spring:
  profiles: prod
guru:
  username: ProdUserName
  password: ProdPwd
  jdbcurl: ProdJdbcUrl
